baseurl: https://ghl-ball.github.io/solving-baseball/
languageCode: ja
title: Solving Baseball Blog
theme: hugo-theme-stack

capitalizeListTitles: false

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  mainSections:
    - analysis
    - breakdown
    - memo
  featuredImageField: image
  rssFullContent: false
  favicon: /solving-baseball/images/favicon.png
  
  footer:
    since: 2025
    customText: トレバ-(^o^)丿
    
  dateFormat:
    published: 2006-01-02
    lastUpdated: 2006-01-02 15:04
    
  sidebar:
    subtitle: Aspiring Saberistの備忘録
    avatar:
      enabled: false
      
  article:
    math: true
    toc: true
    readingTime: true
    license:
      enabled: false
      
  comments:
    enabled: true
    provider: giscus
    giscus:
      repo: "GHL-Ball/solving-baseball"
      repoId: "R_kgDOQbQpuw"
      category: "Announcements"
      categoryId: "DIC_kwDOQbQpu84CzMFQ"
      mapping: "pathname"
      reactionsEnabled: 1
      emitMetadata: 0
      inputPosition: "bottom"
      theme: "preferred_color_scheme"
      lang: "ja"
    
  widgets:
    homepage:
      - type: search
      - type: archives
        params:
          limit: 10
      - type: categories
        params:
          limit: 10
      - type: tag-cloud
        params:
          limit: 10
    page:
      - type: toc

  colorScheme:
    toggle: true
    default: auto

  imageProcessing:
    cover:
      enabled: true
    content:
      enabled: true

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: about
      name: About
      url: /about/
      weight: 2
    - identifier: breakdown
      name: 解説系
      url: /breakdown/
      weight: 3
    - identifier: analysis
      name: 分析系
      url: /analysis/
      weight: 4
    - identifier: memo
      name: メモ
      url: /memo/
      weight: 5
    - identifier: search
      name: 検索
      url: /page/search/
      weight: 6
      
  social:
    - identifier: twitter
      name: Twitter
      url: https://x.com/GHiLiBall
      weight: 10
      params:
        icon: brand-twitter 
    - identifier: note
      name: note
      url: https://note.com/calm_phlox375
      weight: 20
      params:
        icon: link

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    endLevel: 4
    ordered: false
    startLevel: 2
  highlight:
    noClasses: false
    codeFences: true
    guessSyntax: true
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    tabWidth: 4